name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and Deploy React app to GitHub Pages
      uses: omkartapale/react-deployment-gh-pages@v1.0.0
      with:
        build-dir: build

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Add and Commit changes
      run: |
        git add build --all
        git commit -m "Deploy to GitHub Pages"

    - name: Push changes
      run: git push