name: Outdated package checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]    
    paths:
      - '.github/workflows/outdated.yml'
      - 'src/**'
  
  workflow_dispatch:

jobs:
  outdated-packages-check:
    runs-on: ubuntu-latest

    steps:
      - uses: trossr32/outdated-packages-action@v1.7.0
        with:
          use-npm-outdated: true